const ITEM_CODE = '002';
const DISCOUNT_PERCENT = 10;
const THRESHOLD = 30;
const CURRENCY = '€';
const MIN_ITEM = 2;
const DISCOUNT = 3.99;

export { ITEM_CODE, DISCOUNT_PERCENT, THRESHOLD, CURRENCY, MIN_ITEM, DISCOUNT };
